-- CREA PERSONA
DELIMITER $$
CREATE TRIGGER createPersona BEFORE INSERT ON Persona
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRES = UPPER(NEW.NOMBRES);
        SET NEW.APELLIDOS = UPPER(NEW.APELLIDOS);
        SET NEW.DIRECCION = UPPER(NEW.DIRECCION);
    END$$

-- CREA CAMPO
DELIMITER $$
CREATE TRIGGER createCampo BEFORE INSERT ON campo
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
    END $$  

--CREA DISTRITO
CREATE TRIGGER createDistrito BEFORE INSERT ON distrito
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
    END $$ 

--CREA IGLESIA
CREATE TRIGGER createIglesia BEFORE INSERT ON iglesia
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
    END $$ 

-- CREA ESCUELA SABÁTICA
CREATE TRIGGER createEscuela BEFORE INSERT ON escuela
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
    END $$   

-- CREA GRUPO PEQUEÑO
CREATE TRIGGER createGrupo BEFORE INSERT ON grupo
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
        SET NEW.LUG_REUNION = UPPER(NEW.LUG_REUNION);
    END $$

-- CREA MINISTERIO
CREATE TRIGGER createMinisterio BEFORE INSERT ON ministerio
    FOR EACH ROW
    BEGIN
        SET NEW.NOMBRE = UPPER(NEW.NOMBRE);
    END $$
