
SELECT * FROM vtrabmisionero;

DELIMITER $$
CREATE PROCEDURE GET_TRABMISIONERO_GP(IDGP INTEGER)
BEGIN
    SELECT `idDISCIPULADOR`,`DISCIPULADOR`,`idDISCIPULADO`, `DISCIPULADO`,
     `idTRABMISIONERO`, `LECCION`,`FECHA`
    FROM vtrabmisionero
    WHERE `idGRUPO`=IDGP;
END$$
DELIMITER $$
CREATE PROCEDURE GET_TRABMISIONERO_ES(IDES INTEGER)
BEGIN
    SELECT `idDISCIPULADOR`,`DISCIPULADOR`,`idDISCIPULADO`, `DISCIPULADO`,
     `idTRABMISIONERO`, `LECCION`,`FECHA`
    FROM vtrabmisionero
    WHERE `idGRUPO`=IDGP;
END$$

SELECT `idESCUELA`, `ESCUELA`,`idGRUPO`, `GRUPO`, COUNT(`GRUPO`) CANT
    FROM vtrabmisionero
    WHERE `idESCUELA`=5
    GROUP BY `idESCUELA`, `ESCUELA`,`idGRUPO`, `GRUPO`;

CALL GET_LINK(527);

CALL LOGIN('72871525','72871525');