DELIMITER $$
CREATE PROCEDURE LIST_ASISTENCIAMI (IDMINISTERIOi INTEGER)
BEGIN
SELECT P.IDPERSONA, MG.IDMIEMBROMI, P.NOMBRES, P.APELLIDOS,P.DNI,P.TELEFONO,P.FE_NACIMIENTO,
 GET_PORCENT_ASISTMI(MG.IDMIEMBROMI) as PORCENTAJE
FROM MINISTERIO M, MIEMBROMI MG, PERSONA P
WHERE
MG.IDPERSONA = P.IDPERSONA
AND M.IDMINISTERIO=MG.IDMINISTERIO
AND MG.ESTADO='1'
AND M.IDMINISTERIO=IDMINISTERIOi;
END$$